bài 3.2

In [1]:
import numpy as np

arr = np.arange(10)
print("Mảng arr:", arr)
print("Kiểu dữ liệu:", arr.dtype)
print("Kích thước mảng:", arr.shape)

arr_odd = arr[arr % 2 == 1]
arr_even = arr[arr % 2 == 0]
print("Các phần tử lẻ (arr_odd):", arr_odd)
print("Các phần tử chẵn (arr_even):", arr_even)

arr_update_1 = np.where(arr % 2 == 0, arr, 100)
print("Mảng arr_update_1:", arr_update_1)

Mảng arr: [0 1 2 3 4 5 6 7 8 9]
Kiểu dữ liệu: int64
Kích thước mảng: (10,)
Các phần tử lẻ (arr_odd): [1 3 5 7 9]
Các phần tử chẵn (arr_even): [0 2 4 6 8]
Mảng arr_update_1: [  0 100   2 100   4 100   6 100   8 100]


Bài 3.3

In [2]:
import numpy as np

arr_a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr_b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

arr_c = np.intersect1d(arr_a, arr_b)
print("arr_c (phần tử có ở cả arr_a và arr_b):", arr_c)

arr_d = np.setdiff1d(arr_a, arr_b)
print("arr_d (chỉ xuất hiện ở arr_a):", arr_d)

arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print("arr_f (các phần tử từ 5 đến 10):", arr_f)

arr_c (phần tử có ở cả arr_a và arr_b): [2 4]
arr_d (chỉ xuất hiện ở arr_a): [1 3 5 6]
arr_f (các phần tử từ 5 đến 10): [ 6  9 10  8  6]


Bài 3.4

In [3]:
import numpy as np

arr_zeros = np.zeros(10, dtype=int)
arr_zeros[5] = 1
print("Câu 1:", arr_zeros)

arr_h = np.arange(10, 25)
print("Câu 2:", arr_h[::-1])

arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_1 = arr_k[arr_k != 0]
print("Câu 3:", arr_1)

arr_2 = np.append(arr_1, [10, 20])
print("Câu 4:", arr_2)

arr_3 = np.insert(arr_2, 5, 100)
print("Câu 5:", arr_3)

arr_final = np.delete(arr_3, [0, 1, 2])
print("Câu 6:", arr_final)

Câu 1: [0 0 0 0 0 1 0 0 0 0]
Câu 2: [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Câu 3: [1 2 8 2 1 3 5]
Câu 4: [ 1  2  8  2  1  3  5 10 20]
Câu 5: [  1   2   8   2   1 100   3   5  10  20]
Câu 6: [  2   1 100   3   5  10  20]


Bài 3.5

In [5]:
import numpy as np

with open("heights_1.txt", "r") as f:
    height = [float(line.strip()) for line in f.readlines()]

with open("weights_1.txt", "r") as f:
    weight = [float(line.strip()) for line in f.readlines()]

arr_height = np.array(height)
print("Arr_height:", arr_height)

arr_weight = np.array(weight)
print("Arr_weight:", arr_weight)

inch_to_m = 0.0254
pound_to_kg = 0.453592

arr_height_m = arr_height * inch_to_m
arr_weight_kg = arr_weight * pound_to_kg

print("Arr_height_m:", arr_height_m)
print("Arr_weight_kg:", arr_weight_kg)

arr_bmi = arr_weight_kg / (arr_height_m ** 2)
print("Arr_BMI:", arr_bmi)

weight_index_50 = arr_weight_kg[50]
print("Cân nặng tại index 50:", weight_index_50)

arr_height_m_100 = arr_height_m[100:111]
print("Arr_height_m_100:", arr_height_m_100)

players_bmi_under21 = arr_bmi[arr_bmi < 21]
print("Cầu thủ có BMI < 21:", players_bmi_under21)

avg_height = np.mean(arr_height_m)
avg_weight = np.mean(arr_weight_kg)
print("Chiều cao trung bình (m):", avg_height)
print("Cân nặng trung bình (kg):", avg_weight)

max_height = np.max(arr_height_m)
max_weight = np.max(arr_weight_kg)
print("Chiều cao lớn nhất (m):", max_height)
print("Cân nặng lớn nhất (kg):", max_weight)

min_height = np.min(arr_height_m)
min_weight = np.min(arr_weight_kg)
print("Chiều cao nhỏ nhất (m):", min_height)
print("Cân nặng nhỏ nhất (kg):", min_weight)


Arr_height: [70. 58. 78. 70. 58. 69. 70. 58. 78. 70. 58. 69. 58. 78. 70. 58. 69. 70.
 58. 78. 70. 58. 69. 70. 58. 78. 70. 58. 69. 70. 58. 78. 70. 58. 69. 70.
 58. 78. 70. 58. 69. 70. 58. 78. 70. 58. 69. 70. 58. 78. 70. 58. 69.]
Arr_weight: [175. 180. 175. 177. 180. 183. 175. 180. 175. 177. 180. 183. 175. 180.
 175. 177. 180. 183. 175. 180. 175. 177. 180. 183. 175. 180. 175. 177.
 180. 183. 175. 180. 175. 177. 180. 183. 175. 180. 175. 177. 180. 183.
 175. 180. 175. 177. 180. 183. 175. 180. 175. 177. 180.]
Arr_height_m: [1.778  1.4732 1.9812 1.778  1.4732 1.7526 1.778  1.4732 1.9812 1.778
 1.4732 1.7526 1.4732 1.9812 1.778  1.4732 1.7526 1.778  1.4732 1.9812
 1.778  1.4732 1.7526 1.778  1.4732 1.9812 1.778  1.4732 1.7526 1.778
 1.4732 1.9812 1.778  1.4732 1.7526 1.778  1.4732 1.9812 1.778  1.4732
 1.7526 1.778  1.4732 1.9812 1.778  1.4732 1.7526 1.778  1.4732 1.9812
 1.778  1.4732 1.7526]
Arr_weight_kg: [79.3786   81.64656  79.3786   80.285784 81.64656  83.007336 79.3786
 81.64656  79.37

Bài 3.6

In [6]:
import numpy as np

arr = np.full((3, 3), True)
print("Câu 1:\n", arr)

arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
print("\nCâu 2 - arr_2D ban đầu:\n", arr_2D)

arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\nCâu 2 - sau đổi cột 1 và 3:\n", arr_2D)

arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("\nCâu 3 - sau đổi dòng 1 và 2:\n", arr_2D)

arr_2D = arr_2D[::-1, :]
print("\nCâu 4 - đảo ngược dòng:\n", arr_2D)

arr_2D = arr_2D[:, ::-1]
print("\nCâu 5 - đảo ngược cột:\n", arr_2D)

arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])
has_null = np.isnan(arr_2D_null).any()
print("\nCâu 6 - có giá trị null không?", has_null)

arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\nCâu 7 - thay null bằng 0:\n", arr_2D_null)

Câu 1:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

Câu 2 - arr_2D ban đầu:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Câu 2 - sau đổi cột 1 và 3:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]

Câu 3 - sau đổi dòng 1 và 2:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]

Câu 4 - đảo ngược dòng:
 [[8 7 6]
 [2 1 0]
 [5 4 3]]

Câu 5 - đảo ngược cột:
 [[6 7 8]
 [0 1 2]
 [3 4 5]]

Câu 6 - có giá trị null không? True

Câu 7 - thay null bằng 0:
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]


Bài 3.7

In [7]:
import numpy as np

baseball = []
with open("baseball_2D.txt", "r") as f:
    for line in f:
        # Chia dòng theo khoảng trắng và chuyển thành float
        row = [float(x) for x in line.strip().split()]
        baseball.append(row)

np_baseball = np.array(baseball)
print("Kiểu dữ liệu:", np_baseball.dtype)
print("Kích thước:", np_baseball.shape)

print("Dòng thứ 50:", np_baseball[49])

np_weight = np_baseball[:, 1]
print("10 giá trị đầu của np_weight:", np_weight[:10])

height_124 = np_baseball[123, 0]
print("Chiều cao vận động viên thứ 124:", height_124)

avg_height = np.mean(np_baseball[:, 0])
avg_weight = np.mean(np_baseball[:, 1])
print("Chiều cao trung bình:", avg_height)
print("Cân nặng trung bình:", avg_weight)

correlation = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])[0, 1]
print("Hệ số tương quan chiều cao - cân nặng:", correlation)

if correlation > 0:
    print("Nhận xét: Có tương quan thuận giữa chiều cao và cân nặng.")
elif correlation < 0:
    print("Nhận xét: Có tương quan nghịch giữa chiều cao và cân nặng.")
else:
    print("Nhận xét: Không có tương quan rõ ràng giữa chiều cao và cân nặng.")

Kiểu dữ liệu: float64
Kích thước: (130, 2)
Dòng thứ 50: [ 79. 187.]
10 giá trị đầu của np_weight: [178. 178. 190. 186. 187. 178. 178. 190. 186. 187.]
Chiều cao vận động viên thứ 124: 78.0
Chiều cao trung bình: 75.8
Cân nặng trung bình: 183.8
Hệ số tương quan chiều cao - cân nặng: 0.9624910372928001
Nhận xét: Có tương quan thuận giữa chiều cao và cân nặng.


Bài 3.8

In [9]:
import numpy as np

with open("heights.txt", "r") as f:
    heights = [float(line.strip()) for line in f.readlines()]

with open("positions.txt", "r") as f:
    positions = [line.strip() for line in f.readlines()]
# 1
# a) Numpy array từ list positions
np_positions = np.array(positions)
print("Kiểu dữ liệu np_positions:", np_positions.dtype)

# b) Numpy array từ list heights
np_heights = np.array(heights)
print("Kiểu dữ liệu np_heights:", np_heights.dtype)

# 2. Chiều cao trung bình của GK
avg_height_GK = np.mean(np_heights[np_positions == 'GK'])
print("Chiều cao trung bình của GK:", avg_height_GK)

# 3. Chiều cao trung bình của các vị trí khác (không phải GK)
avg_height_other = np.mean(np_heights[np_positions != 'GK'])
print("Chiều cao trung bình của các vị trí khác:", avg_height_other)

# 4. Tạo mảng structured array với 'position' kiểu U5 và 'height' kiểu float
players = np.array(list(zip(np_positions, np_heights)),
                   dtype=[('position', 'U5'), ('height', 'f4')])
print("Structured array players:\n", players[:10])

# 5. Sắp xếp mảng players theo height
players_sorted = np.sort(players, order='height')
print("Players sắp xếp theo height:\n", players_sorted[:10])

# Chiều cao thấp nhất và cao nhất
min_player = players_sorted[0]
max_player = players_sorted[-1]

print("Chiều cao thấp nhất:", min_player['height'], "- vị trí:", min_player['position'])
print("Chiều cao cao nhất:", max_player['height'], "- vị trí:", max_player['position'])

Kiểu dữ liệu np_positions: <U2
Kiểu dữ liệu np_heights: float64
Chiều cao trung bình của GK: 71.66666666666667
Chiều cao trung bình của các vị trí khác: 66.53191489361703
Structured array players:
 [('M', 70.) ('A', 58.) ('D', 78.) ('M', 70.) ('GK', 58.) ('A', 69.)
 ('D', 70.) ('M', 58.) ('A', 78.) ('M', 70.)]
Players sắp xếp theo height:
 [('A', 58.) ('A', 58.) ('D', 58.) ('D', 58.) ('D', 58.) ('D', 58.)
 ('D', 58.) ('GK', 58.) ('M', 58.) ('M', 58.)]
Chiều cao thấp nhất: 58.0 - vị trí: A
Chiều cao cao nhất: 78.0 - vị trí: M


Bài 3.9

In [10]:
import pandas as pd

# 1. Tạo DataFrame euro12 từ file euro2012.csv
euro12 = pd.read_csv("euro2012.csv")

# In type, shape, danh sách các cột
print("Type:", type(euro12))
print("Shape:", euro12.shape)
print("Danh sách các cột:", euro12.columns.tolist())

# 2. In giá trị cột Goals
print("\nCột Goals:\n", euro12['Goals'])

# 3. Có bao nhiêu đội tham gia Euro2012
num_teams = euro12['Team'].nunique()
print("\nSố đội tham gia Euro 2012:", num_teams)

# 4. In thông tin DataFrame
print("\nThông tin DataFrame Euro12:")
print(euro12.info())

# 5. Tạo DataFrame discipline chỉ chứa 3 cột 'Team', 'Yellow Cards', 'Red Cards'
discipline = euro12[['Team', 'Yellow Cards', 'Red Cards']]
print("\nDiscipline:\n", discipline)

# 6. Sắp xếp discipline giảm dần theo 'Red Cards', 'Yellow Cards'
discipline_sorted = discipline.sort_values(by=['Red Cards', 'Yellow Cards'], ascending=False)
print("\nDiscipline sắp xếp:\n", discipline_sorted)

# 7a. Trung bình Yellow Cards
avg_yellow = euro12['Yellow Cards'].mean()
print("\nTrung bình Yellow Cards:", avg_yellow)

# 7b. Lọc các đội ghi hơn 6 bàn thắng
teams_goals_over6 = euro12[euro12['Goals'] > 6]
print("\nĐội ghi hơn 6 bàn thắng:\n", teams_goals_over6[['Team', 'Goals']])

# 8. In các đội tên bắt đầu bằng 'G'
teams_start_G = euro12[euro12['Team'].str.startswith('G')]
print("\nĐội tên bắt đầu bằng 'G':\n", teams_start_G['Team'])

# 9. In 7 cột đầu của euro12
print("\n7 cột đầu:\n", euro12.iloc[:, :7])

# 10. In tất cả các cột trừ 3 cột cuối
print("\nTất cả cột trừ 3 cột cuối:\n", euro12.iloc[:, :-3])

# 11. In các cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards
cols_selected = ['Team', 'Goals', 'Shooting Accuracy', 'Yellow Cards', 'Red Cards']
print("\nCác cột Team, Goals, Shooting Accuracy, Yellow Cards, Red Cards:\n", euro12[cols_selected])

# 12. Chỉ hiển thị 'Team','Shooting Accuracy' từ 'England', 'Italy', 'Russia'
teams_selected = euro12[euro12['Team'].isin(['England', 'Italy', 'Russia'])]
print("\nTeam và Shooting Accuracy cho England, Italy, Russia:\n", teams_selected[['Team','Shooting Accuracy']])

Type: <class 'pandas.core.frame.DataFrame'>
Shape: (16, 8)
Danh sách các cột: ['Team', 'Goals', 'Shots', 'OnTarget', 'Passes', 'Yellow Cards', 'Red Cards', 'Shooting Accuracy']

Cột Goals:
 0     4
1     6
2     6
3     2
4     4
5     8
6     2
7     1
8     1
9     5
10    3
11    1
12    3
13    2
14    1
15    1
Name: Goals, dtype: int64

Số đội tham gia Euro 2012: 16

Thông tin DataFrame Euro12:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Team               16 non-null     object 
 1   Goals              16 non-null     int64  
 2   Shots              16 non-null     int64  
 3   OnTarget           16 non-null     int64  
 4   Passes             16 non-null     int64  
 5   Yellow Cards       16 non-null     int64  
 6   Red Cards          16 non-null     int64  
 7   Shooting Accuracy  16 non-null     float64
dtypes: float6